Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = 3072
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end

(1..3).each do |i|
    config.vm.define "kafka#{i}" do |node|
        node.vm.hostname = "kafka#{i}.lab.com"
        node.vm.network "private_network", ip: "192.168.33.2#{i}"
    end
end

end
